"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.verifyBoletins = exports.updatesOpenInBrowser = exports.sendBugReport = exports.removeThisFavorite = exports.openInBrowser = exports.initCarrourcel = exports.goToThisNotifyClick = exports.getVersionDetails = exports.getThisBoletimById = exports.getNotifications = exports.getNotificationList = exports.getNotificationGrid = exports.getFavoriteList = exports.getConfigurations = exports.getClassificadoresList = exports.getClassificadorById = exports.getBoletimList = exports.favoriteThisClassificador = exports.favoriteThisBe = exports.configurationProcess = exports.checkDbStatus = exports.changeNotifyCL = exports.changeNotifyBE = exports.allNotificationReaded = void 0;
var allNotificationReaded_1 = require("./allNotificationReaded");
__createBinding(exports, allNotificationReaded_1, "default", "allNotificationReaded");
var changeNotifyBE_1 = require("./changeNotifyBE");
__createBinding(exports, changeNotifyBE_1, "default", "changeNotifyBE");
var changeNotifyCL_1 = require("./changeNotifyCL");
__createBinding(exports, changeNotifyCL_1, "default", "changeNotifyCL");
var checkDbStatus_1 = require("./checkDbStatus");
__createBinding(exports, checkDbStatus_1, "default", "checkDbStatus");
var configurationProcess_1 = require("./configurationProcess");
__createBinding(exports, configurationProcess_1, "default", "configurationProcess");
var favoriteThisBe_1 = require("./favoriteThisBe");
__createBinding(exports, favoriteThisBe_1, "default", "favoriteThisBe");
var favoriteThisClassificador_1 = require("./favoriteThisClassificador");
__createBinding(exports, favoriteThisClassificador_1, "default", "favoriteThisClassificador");
var getBoletimList_1 = require("./getBoletimList");
__createBinding(exports, getBoletimList_1, "default", "getBoletimList");
var getClassificadorById_1 = require("./getClassificadorById");
__createBinding(exports, getClassificadorById_1, "default", "getClassificadorById");
var getClassificadoresList_1 = require("./getClassificadoresList");
__createBinding(exports, getClassificadoresList_1, "default", "getClassificadoresList");
var getConfigurations_1 = require("./getConfigurations");
__createBinding(exports, getConfigurations_1, "default", "getConfigurations");
var getFavoriteList_1 = require("./getFavoriteList");
__createBinding(exports, getFavoriteList_1, "default", "getFavoriteList");
var getNotificationGrid_1 = require("./getNotificationGrid");
__createBinding(exports, getNotificationGrid_1, "default", "getNotificationGrid");
var getNotificationList_1 = require("./getNotificationList");
__createBinding(exports, getNotificationList_1, "default", "getNotificationList");
var getNotifications_1 = require("./getNotifications");
__createBinding(exports, getNotifications_1, "default", "getNotifications");
var getThisBoletimById_1 = require("./getThisBoletimById");
__createBinding(exports, getThisBoletimById_1, "default", "getThisBoletimById");
var getVersionDetails_1 = require("./getVersionDetails");
__createBinding(exports, getVersionDetails_1, "default", "getVersionDetails");
var goToThisNotifyClick_1 = require("./goToThisNotifyClick");
__createBinding(exports, goToThisNotifyClick_1, "default", "goToThisNotifyClick");
var initCarrourcel_1 = require("./initCarrourcel");
__createBinding(exports, initCarrourcel_1, "default", "initCarrourcel");
var openInBrowser_1 = require("./openInBrowser");
__createBinding(exports, openInBrowser_1, "default", "openInBrowser");
var removeThisFavorite_1 = require("./removeThisFavorite");
__createBinding(exports, removeThisFavorite_1, "default", "removeThisFavorite");
var sendBugReport_1 = require("./sendBugReport");
__createBinding(exports, sendBugReport_1, "default", "sendBugReport");
var updatesOpenInBrowser_1 = require("./updatesOpenInBrowser");
__createBinding(exports, updatesOpenInBrowser_1, "default", "updatesOpenInBrowser");
var verifyBoletins_1 = require("./verifyBoletins");
__createBinding(exports, verifyBoletins_1, "default", "verifyBoletins");
//# sourceMappingURL=index.js.map